namespace ChatAIze.PerfectEmail.Test;

[TestClass]
public class EmailValidatorTest
{
    [TestMethod]
    [DataRow(null, false)]
        [DataRow("", false)]
        [DataRow("        ", false)]
        [DataRow("a", false)]
        [DataRow("@", false)]
        [DataRow(".@", false)]
        [DataRow("@.", false)]
        [DataRow(".@.", false)]
        [DataRow(".@.a", false)]
        [DataRow("-@a.aa", false)]
        [DataRow("+@a.aa", false)]
        [DataRow(" a@a.aa", false)]
        [DataRow("a@a.aa ", false)]
        [DataRow("a@a.aa.", false)]
        [DataRow("a@a.a", false)]
        [DataRow("a@a.a1", false)]
        [DataRow("a@a.11", false)]
        [DataRow("a@aa.aa", true)]
        [DataRow("a@a.aa", true)]
        [DataRow("a@aa.a.aa", true)]
        [DataRow("a.a@a.aa", true)]
        [DataRow("a.a@a1.aa", true)]
        [DataRow("a-a@a.aa", true)]
        [DataRow("a--a@a.aa", true)]
        [DataRow("a--a@a-a.aa", true)]
        [DataRow("a+a@a.aa", true)]
        [DataRow("a++a@a.aa", true)]
        [DataRow("a@a+.aa", false)]
        [DataRow("a@a@a.aa", false)]
        [DataRow(".a@a.aa", false)]
        [DataRow("a.@a.aa", false)]
        [DataRow("a..a@a.aa", false)]
        [DataRow("a@..a.aa", false)]
        [DataRow("a@.a.aa", false)]
        [DataRow("a@a..aa", false)]
        [DataRow("a.-a@a.aa", false)]
        [DataRow("a.+a@a.aa", false)]
        [DataRow("a._a@a.aa", false)]
        [DataRow("a@a-.aa", false)]
        [DataRow("a@aa.a-a", false)]
        [DataRow("a@aa.aa.a", false)]
        [DataRow("a_a@a.aa", true)]
        [DataRow("a1_a2@a.aa", true)]
        [DataRow("a.a_a@a.aa", true)]
        [DataRow("a_a.a@a.aa", true)]
        [DataRow("_a@a.aa", false)]
        [DataRow("a_@a.aa", false)]
        [DataRow("a__a@a.aa", false)]
        [DataRow("a_.a@a.aa", false)]
        [DataRow("a@a_a.aa", false)]
        [DataRow("a@_a.aa", false)]
        [DataRow("a@a_.aa", false)]
        [DataRow("a@a._aa", false)]
        [DataRow("a@a.aa_", false)]
    public void IsValidEmailTest(string? email, bool expected)
    {
        var actual = EmailValidator.IsValidEmail(email);
        Assert.AreEqual(expected, actual);
    }
}
